#!/bin/sh /etc/rc.common

START=96
STOP=96

PATH=/opt/sbin:/opt/bin:/opt/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

start() {
	logger -t softether "Starting smartvpn..."
	softeher_vpn.sh on
}

stop() {
	logger -t softether "Stoping smartvpn..."
	softeher_vpn.sh off
}

restart() {
	start
	stop
}

reload() {
        restart
        return $?
}
